input_url,normalized_url,host,tls_handshake_ok,cert_subject_cn,cert_san_list,hostname_match,not_before_utc,not_after_utc,days_to_expiry,issuer_cn,serial_hex,http_status,final_url,redirect_chain,http_note,error,expired,expiring_7d,expiring_30d,cert_mismatch,final_is_http,has_insecure_note,severity,recommended_action
https://common-mqtt-st.ruic.lgthinq.com,https://common-mqtt-st.ruic.lgthinq.com,common-mqtt-st.ruic.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='common-mqtt-st.ruic.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF46E90>: Failed to resolve 'common-mqtt-st.ruic.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://common-qa.iot.ruic.lgthinq.com,https://common-qa.iot.ruic.lgthinq.com,common-qa.iot.ruic.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='common-qa.iot.ruic.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF59450>: Failed to resolve 'common-qa.iot.ruic.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://common.iot.ruic.lgthinq.com,https://common.iot.ruic.lgthinq.com,common.iot.ruic.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='common.iot.ruic.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF58F50>: Failed to resolve 'common.iot.ruic.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://eic-laundry-dv.lgthinq.com,https://eic-laundry-dv.lgthinq.com,eic-laundry-dv.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='eic-laundry-dv.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF58CD0>: Failed to resolve 'eic-laundry-dv.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://eic-st-3rdparty.lgthinq.com,https://eic-st-3rdparty.lgthinq.com,eic-st-3rdparty.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='eic-st-3rdparty.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF58550>: Failed to resolve 'eic-st-3rdparty.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://eu.lgthinq.com,https://eu.lgthinq.com,eu.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='eu.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF59BD0>: Failed to resolve 'eu.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://hadms-us-dev.lgthinq.com,https://hadms-us-dev.lgthinq.com,hadms-us-dev.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='hadms-us-dev.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF59F90>: Failed to resolve 'hadms-us-dev.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://hcss-build.lgthinq.com,https://hcss-build.lgthinq.com,hcss-build.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='hcss-build.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF46E90>: Failed to resolve 'hcss-build.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://he-ru-ai.lgthinq.com,https://he-ru-ai.lgthinq.com,he-ru-ai.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='he-ru-ai.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF45310>: Failed to resolve 'he-ru-ai.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://kic-dv-lss.lgthinq.com,https://kic-dv-lss.lgthinq.com,kic-dv-lss.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='kic-dv-lss.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF44B90>: Failed to resolve 'kic-dv-lss.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://kic-laundry-dv.lgthinq.com,https://kic-laundry-dv.lgthinq.com,kic-laundry-dv.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='kic-laundry-dv.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF44690>: Failed to resolve 'kic-laundry-dv.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://kic-laundry.lgthinq.lgthinq.com,https://kic-laundry.lgthinq.lgthinq.com,kic-laundry.lgthinq.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='kic-laundry.lgthinq.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF46850>: Failed to resolve 'kic-laundry.lgthinq.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://kic-st-turn2.lgthinq.com,https://kic-st-turn2.lgthinq.com,kic-st-turn2.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='kic-st-turn2.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF47B10>: Failed to resolve 'kic-st-turn2.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://laundry-dv.lgthinq.com,https://laundry-dv.lgthinq.com,laundry-dv.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='laundry-dv.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769BEA5310>: Failed to resolve 'laundry-dv.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://laundry-dv.lgthinq.lgthinq.com,https://laundry-dv.lgthinq.lgthinq.com,laundry-dv.lgthinq.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='laundry-dv.lgthinq.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF1AC10>: Failed to resolve 'laundry-dv.lgthinq.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://new-eic-ext.lgthinq.com,https://new-eic-ext.lgthinq.com,new-eic-ext.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='new-eic-ext.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF2A350>: Failed to resolve 'new-eic-ext.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://onpremiss-iot2.lgthinq.com,https://onpremiss-iot2.lgthinq.com,onpremiss-iot2.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='onpremiss-iot2.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF29310>: Failed to resolve 'onpremiss-iot2.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://opip.lgthinq.com,https://opip.lgthinq.com,opip.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='opip.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF2BED0>: Failed to resolve 'opip.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://route.laundry.lgthinq.com,https://route.laundry.lgthinq.com,route.laundry.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='route.laundry.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF59BD0>: Failed to resolve 'route.laundry.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic.lgthinq.com,https://ruic.lgthinq.com,ruic.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF58550>: Failed to resolve 'ruic.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-common.lgthinq.com,https://ruic-common.lgthinq.com,ruic-common.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-common.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF58E10>: Failed to resolve 'ruic-common.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-internal.lgthinq.com,https://ruic-internal.lgthinq.com,ruic-internal.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-internal.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF591D0>: Failed to resolve 'ruic-internal.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-iotservice.lgthinq.com,https://ruic-iotservice.lgthinq.com,ruic-iotservice.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-iotservice.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF59590>: Failed to resolve 'ruic-iotservice.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-laundry.lgthinq.com,https://ruic-laundry.lgthinq.com,ruic-laundry.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-laundry.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF5A350>: Failed to resolve 'ruic-laundry.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-media.lgthinq.com,https://ruic-media.lgthinq.com,ruic-media.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-media.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF2BED0>: Failed to resolve 'ruic-media.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-mqtt.lgthinq.com,https://ruic-mqtt.lgthinq.com,ruic-mqtt.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-mqtt.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF2A210>: Failed to resolve 'ruic-mqtt.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-objectstore.lgthinq.com,https://ruic-objectstore.lgthinq.com,ruic-objectstore.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-objectstore.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CED20D0>: Failed to resolve 'ruic-objectstore.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-qa-common.lgthinq.com,https://ruic-qa-common.lgthinq.com,ruic-qa-common.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-qa-common.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF1A990>: Failed to resolve 'ruic-qa-common.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-qa-iotservice.lgthinq.com,https://ruic-qa-iotservice.lgthinq.com,ruic-qa-iotservice.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-qa-iotservice.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CEF56D0>: Failed to resolve 'ruic-qa-iotservice.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-qa-objectstore.lgthinq.com,https://ruic-qa-objectstore.lgthinq.com,ruic-qa-objectstore.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-qa-objectstore.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF479D0>: Failed to resolve 'ruic-qa-objectstore.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-qa-service.lgthinq.com,https://ruic-qa-service.lgthinq.com,ruic-qa-service.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-qa-service.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF46350>: Failed to resolve 'ruic-qa-service.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-qa-service-internal.lgthinq.com,https://ruic-qa-service-internal.lgthinq.com,ruic-qa-service-internal.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-qa-service-internal.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF44050>: Failed to resolve 'ruic-qa-service-internal.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-report.lgthinq.com,https://ruic-report.lgthinq.com,ruic-report.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-report.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF44CD0>: Failed to resolve 'ruic-report.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-service.lgthinq.com,https://ruic-service.lgthinq.com,ruic-service.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-service.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF45810>: Failed to resolve 'ruic-service.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-service-internal.lgthinq.com,https://ruic-service-internal.lgthinq.com,ruic-service-internal.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-service-internal.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF46FD0>: Failed to resolve 'ruic-service-internal.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://ruic-t1api.lgthinq.com,https://ruic-t1api.lgthinq.com,ruic-t1api.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='ruic-t1api.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF596D0>: Failed to resolve 'ruic-t1api.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://usdownload.lgthinq.com,https://usdownload.lgthinq.com,usdownload.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='usdownload.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF59450>: Failed to resolve 'usdownload.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://usdownload-dev.lgthinq.com,https://usdownload-dev.lgthinq.com,usdownload-dev.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='usdownload-dev.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF58B90>: Failed to resolve 'usdownload-dev.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://usdownload-st.lgthinq.com,https://usdownload-st.lgthinq.com,usdownload-st.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='usdownload-st.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF58410>: Failed to resolve 'usdownload-st.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://www.lgthinq.com,https://www.lgthinq.com,www.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='www.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF59810>: Failed to resolve 'www.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
https://www.lgthinq.com,https://www.lgthinq.com,www.lgthinq.com,False,,,,,,,,,,,,"HTTP head error: HTTPSConnectionPool(host='www.lgthinq.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x000002769CF5A0D0>: Failed to resolve 'www.lgthinq.com' ([Errno 11001] getaddrinfo failed)""))",TLS connect error: [Errno 11001] getaddrinfo failed / fallback: [Errno 11001] getaddrinfo failed,False,False,False,False,False,False,Low,No immediate action required
